_target_: src.models.gconvloc_localize_module_sle.LocalizationModule

hidden_channels: [256, 128]
activation: "relu"
heads: 1
conv_dropout: 0.0
node_dropout: 0.0
edge_dropout: 0.0
add_self_loops: True
fill_value: "max"
share_weights: False
output_activation: "sigmoid"
normalize: True
post_mlp_hiddens: [64]
post_activation: "relu"
post_dropout: 0.0
post_input_dropout: 0.0
use_post_mlp: True
log_dir: ${paths.output_dir}

criterion:
  _target_: torch.nn.MSELoss

optimizer:
      _target_: src.utils.build_optimizer
      _partial_: True
      weight_decay: 0.0
      lr: 0.001
      opt: "adam"
      opt_scheduler: "none"
      opt_decay_step: 1000
      opt_decay_rate: 0.9
      epochs: 20000
