_target_: src.datamodules.UJIIndoorLoc_datamodule_euc_knn_graph.UJIIndoorLocGraphDataModule

root_dir: ${paths.data_dir}/UJIIndoorLoc
top_k: 30
loader: "full"
batch_size: 128
num_workers: 0
num_neighbors: null
